### ISSUE TITLE
Research algorithms to be implemented

### ISSUE THREAD

**Issue by John15321** [John15321/proc-opt#1]
Research algorithms to be implemented

**Comment by John15321** [comment]
Podobna implementacja paczki https://crates.io/crates/mincost

**Comment by applesoju** [comment]
Repo z Sterowania Procesami Dyskretnymi, które współtworzyłem: https://github.com/Mateqo/SPD

**Comment by John15321** [comment]
Moje propozycje narazie to:

* Carlier
* Schrage
* Witi
* Jacksons
* Neh
* Split Schrage
* Simulated Annealing (symulowane wyrzazanie)
* Genetyczny
* Tabu

**Comment by John15321** [comment]
> Moje propozycje narazie to:
> 
> * Carlier
> * Schrage
> * Witi
> * Jacksons
> * Neh
> * Split Schrage
> * Simulated Annealing (symulowane wyrzazanie)
> * Genetyczny
> * Tabu
?
@BlueCookieFrog  @applesoju

**Comment by John15321** [comment]
Moje repo z SPC a paroma algorytmami

**Comment by John15321** [comment]
To implement:
* Carlier
* Schrage
* Genetic Algorithm
* Simulated Annealing
* Particle Swarm
* Tabu Search
