### ISSUE TITLE
Implement Schrage algorithm

### ISSUE THREAD

**Issue by John15321** [John15321/proc-opt#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by applesoju** [comment]
http://new.zsd.iiar.pwr.edu.pl/educ.php?lid=132&zid=SCHRAGE

**Comment by BlueCookieFrog** [comment]
https://github.com/BlueCookieFrog/SPD/blob/main/Lab2/spdl2.pdf

**Comment by John15321** [comment]
http://mariusz.makuchowski.staff.iiar.pwr.wroc.pl/download/courses/sterowanie.procesami.dyskretnymi/lab.instrukcje/lab04.schrage/

**Comment by John15321** [comment]
Done
